### PR TITLE
Fix for Capacitor 5/Angular 16 peer dependencies error

### PR DESCRIPTION
**Pull request by ahunter135**

### CODE REVIEW

**Review by afilp — APPROVED** [review]

**Comment by lucas-zimerman** [comment]
In this case wouldn't it break for uses using the non ivy version of Angular?

**Comment by ahunter135** [comment]
@lucas-zimerman 

It might. I'm new to this. But we also need to do an install and it fails without this. 

Side effect of this change: I'm on capacitor angular, but I can't import it from there. I have to import from sentry/angular-ivy. So there could be more to do here. 

I just wanted to start the discussion back up because at this point, sentry is not supporting capacitor 5 and angular 16.

**Comment by emelampianakis** [comment]
angular 16 needs the ivy distribution. if this is the case maby you can remove the dependency completely so each dev can install the package needed

**Comment by ahunter135** [comment]
So instead of putting ivy in, just remove it entirely? I can do that. @emelampianakis

**Comment by emelampianakis** [comment]
> So instead of putting ivy in, just remove it entirely? I can do that. @emelampianakis

Yeah, I think this is the correct approach, but then the Installation part of the readme should also be updated

**Comment by emelampianakis** [comment]
Hello @ahunter135 can you try the changes I mentioned above?
Just remove both @sentry/angular & @sentry/angular-ivy dependencies and update the readme file.
We really need this fix cause as it is right now angular 16 projects cant use this package.

**Comment by ahunter135** [comment]
@emelampianakis made the requested changes!

**Review by miguel-S73 — APPROVED** [review]

**Comment by afilp** [comment]
@lucas-zimerman Can you please approve and merge the changes so that we can start using the fix soon (with Angular 16)? Thanks a lot!

**Comment by krystofwoldrich** [comment]
Based on https://github.com/getsentry/sentry-capacitor/issues/405#issuecomment-1732593860 the peer deps are not the issue.

Thank you, everyone, for the comments, please use `@sentry/angular-ivy` with Angular 12 and newer.

Follow up PR with readme update from this PR -> https://github.com/getsentry/sentry-capacitor/pull/469

**Pull request closed without merging**
