### PR TITLE
Upgrade to Capacitor 5

### PR DESCRIPTION
**Pull request by borgoat**
https://capacitorjs.com/docs/next/updating/plugins/5-0

Solves #355

### CODE REVIEW

**Comment by borgoat** [comment]
In case anyone else is trying to use this with Capacitor 5, I have prepared yet another branch in my fork with the correct configuration to fetch directly from GitHub. In your `package.json`, change your configuration as follows (tested with yarn):

```
{
  "dependencies": {
    "@sentry/capacitor": "borgoat/sentry-capacitor#head=yarn-2",
    "@sentry/angular": "7.42.0",
    "@sentry/tracing": "7.42.0",
  }
}
```

The separate branch was required because of #360

**Comment by lucas-zimerman** [comment]
Thank you for the PR!
With those changes, will it have any impact on the previous Capacitor versions?

**Comment by borgoat** [comment]
Apologies for the missing entry in the changelog, I'll add it!

As for backwards compatibility, I have not tested with Capacitor 4, but I tend to believe this is indeed a breaking change. I guess whoever uses this version of the plug-in must also use Android Gradle Plugin 8 and thus Capacitor 5.

So I guess it's reasonable if this is not merged until Capacitor 5 is in general availability

**Comment by funkenstrahlen** [comment]
Capacitor 5 is now released officially.

**Comment by borgoat** [comment]
I added the line to the changelog. What I could not do yet is to test with a Capacitor 4 app, but I'm quite sure the Android build will break (unless one is using Capacitor 4 with an incompatible Android configuration with AGP 8 and Java 17...)

My recommendation would be to bump the peer dependencies in the package.json to `^5.0.0`, but I could not do it without migrating the changelog format to yarn 2. As mentioned in this other comment of mine, I think it'd be worth migrating: https://github.com/getsentry/sentry-capacitor/issues/360#issuecomment-1529976062. This would only impact contributors, not users, but it should provide a better developer experience.

**Comment by priyaa05** [comment]
Hi @lucas-zimerman ,
Can we fast track this , as we currently upgraded our app to capacitor 5, but without this change, we can't build the android project.
Thanks,
Priyanka

**Comment by borgoat** [comment]
I have not tested this (still using the fork[^1]), but by the look of it, this workaround in Capacitor 5.0.2[^2] *should* support this plugin and others with a similar config, by patching the Android/Gradle scripts at build time.

It's by no means a definitive solution, but maybe it can help until this gets merged and released.

[^1]: https://github.com/getsentry/sentry-capacitor/pull/356#issuecomment-1521532793
[^2]: https://github.com/ionic-team/capacitor/pull/6577

**Comment by RobSchilderr** [comment]
Who do we need to tag to get it to be reviewed?

**Comment by priyaa05** [comment]
> I have not tested this (still using the fork[1](#user-content-fn-1-badb8cfd2bb0394e211d14d28b68e4b0)), but by the look of it, this workaround in Capacitor 5.0.2[2](#user-content-fn-2-badb8cfd2bb0394e211d14d28b68e4b0) _should_ support this plugin and others with a similar config, by patching the Android/Gradle scripts at build time.
> 
> It's by no means a definitive solution, but maybe it can help until this gets merged and released.
> 
> ## Footnotes
> 1. https://github.com/getsentry/sentry-capacitor/pull/356#issuecomment-1521532793 [↩](#user-content-fnref-1-badb8cfd2bb0394e211d14d28b68e4b0)
> 2. https://github.com/ionic-team/capacitor/pull/6577 [↩](#user-content-fnref-2-badb8cfd2bb0394e211d14d28b68e4b0)

Hi @borgoat ,
Thanks for the reply, but when I use these settings I don't see the updated code after I do npm install. We use node js and our project is ionic with angular.

image

image

Thanks,
Priyanka

**Comment by thmclellan** [comment]
Hi @priyaa05 I had a similar issue and got a build working with a modified fork, see https://github.com/getsentry/sentry-capacitor/issues/355#issuecomment-1562067380

**Comment by Edjevw12** [comment]
I hope this one gets reviewed asap :)

**Comment by danidee10** [comment]
@priyaa05 This is not a solution

I had the same problem (couldn't get it to work with `npm`), but switching to `yarn v2` (same with @borgoat) fixed it

**Comment by thmclellan** [comment]
Thanks @danidee10 for the suggestion, good to know it worked for you after switching to yarn v2.

**Comment by priyaa05** [comment]
> Hi @priyaa05 I had a similar issue and got a build working with a modified fork, see [#355 (comment)](https://github.com/getsentry/sentry-capacitor/issues/355#issuecomment-1562067380)

Thanks @thmclellan  , the fork is working through npm and I am able to capture events too.

**Review by lucas-zimerman — APPROVED** [review]
Thank you for the PR!

**Pull request merged**
