### PR TITLE
Bump Sentry JavaScript 7.1.1

### PR DESCRIPTION
**Pull request by lucas-zimerman**
- [x]  Build pass
- [x]  Test pass
- [x]  Validate on Android
- [x]  Validate on iOS
- [x] Update changelog

### CODE REVIEW

**Comment by bruno-garcia** [comment]
Is this still WIP? it's not draft

**Comment by bruno-garcia** [comment]
Adding @jennmueng in case he wants to review. I just skimmed, are there any breaking changes?

**Comment by lucas-zimerman** [comment]
> Adding @jennmueng in case he wants to review. I just skimmed, are there any breaking changes?

Yes, the most noticeable one was the new way of writing the level of breadcrumbs.

On React Native we added the following changelog:
```
## Breaking changes

By bumping Sentry Javascript, new breaking changes were introduced, to know more what was changed, check the [breaking changes changelog](https://github.com/getsentry/sentry-javascript/blob/7.0.0/CHANGELOG.md#breaking-changes) from Sentry Javascript.

```
this may be enough for showing the break changes?

additionally, just like in RN, I'd like to release this version as a beta.

**Comment by bruno-garcia** [comment]
We're on version `0.x.x` so we should be fine with that note.

We plan to merge this on July 4th once Lucas is back online

**Review by jennmueng — APPROVED** [review]

**Comment by michaeltintiuc** [comment]
Any updates on this? Is there an ETA for a new version? Thanks in advance!

**Comment by lucas-zimerman** [comment]
@bruno-garcia  can we release this as an beta?

**Review by bruno-garcia — APPROVED** [review]

**Pull request merged**
