### PR TITLE
build(deps): bump Sentry for iOS (sentry-cocoa) to 8.8.0

### LINKED ISSUE #396: Update Sentry for iOS (sentry-cocoa) from 7.27.1 to 8.8.0
It is possible to update Sentry for iOS from 7.27.1 to 8.8.0? I tried it locally and it should be working. Is there a reason why it wasn't updated since 12 October 2022?

I will attach the PR soon.

### PR DESCRIPTION
**Pull request by Zapominacz**
Additionaly, fixed formatting issues in plist files

closes #396

### CODE REVIEW

**Comment by bruno-garcia** [comment]
There are really no breaking changes? 
The PR for RN was quite large: v

**Comment by Zapominacz** [comment]
@bruno-garcia You are right - I forgot to change it in `ios/Podfile`. I will repair it as soon as possible

**Comment by Zapominacz** [comment]
@bruno-garcia Have some issues with `PrivateSentrySDKOnly` - should work now. Added `[weak self]` to closures to prevent retain cycles

**Comment by Zapominacz** [comment]
I've rechecked all example apps and performed some adjustments

**Review by bruno-garcia — APPROVED** [review]
LGTM. cc @brustolin

**Review by brustolin — APPROVED** [review]
LGTM

**Pull request merged**
